name: Issue triggered


on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  create_issue:
    runs-on: ubuntu-20.04
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
      - run: echo $MESSAGE


