name: Repository Dispatch
on:
  repository_dispatch:
    types: [pipeline-trigger]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    env:
      CORE_BASE_VERSION: ${{ github.event.client_payload.CORE_BASE_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${CORE_BASE_VERSION}


